name: Build with Maven and run cucumber tests, merge if passed

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
jobs: 
  build-and-test:
  
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "adopt"
          
      - name: Build and run specific test with Maven
        run: mvn test -Dtest="com.github.owengraham.selenium_project.runners.*Test"
        working-directory: framework
