name: Build with Maven and run unit tests, merge if passed

on: 
  push:
    branches: [test]
  pull_request:
    branches: [test]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps: 
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "adopt"
          
      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTesta
        working-directory: framework

  test:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: "22"
          distribution: "adopt"
          
      - name: Run specific tests with Maven
        run: mvn test -Dtest="com.sparta.selenium_project.junit.*Test"
        working-directory: framework
